workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Vercel-API:
        inputs:
            - location: ./vercel-api-suggest.yaml
        registry:
            location: registry.speakeasyapi.dev/vercel/vercel/vercel-api
    vercel-openapi:
        inputs:
            - location: vercel-api-modified.yaml
        registry:
            location: registry.speakeasyapi.dev/vercel/vercel/vercel-openapi
targets:
    typescript:
        target: typescript
        source: vercel-openapi
        output: .
